# Generated by Django 4.2.7 on 2023-11-20 10:33

from django.db import migrations, models
import django.db.models.deletion
import wagtail.blocks
import wagtail.fields
import wagtailutils.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('basepage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pages.basepage')),
                ('body', wagtail.fields.StreamField([('only_text', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(required=False)), ('text', wagtailutils.blocks.RichTextBlock(required=True))])), ('image_and_text', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(required=False)), ('text', wagtailutils.blocks.RichTextBlock(required=False)), ('image', wagtailutils.blocks.ImageChooserBlock(help_text='Optimal Dimension : 441x400', rendition_rules={'original': 'fill-441x400-c0|format-webp', 'original_fallback': 'fill-441x400-c0'}, required=False)), ('image_alignment', wagtail.blocks.ChoiceBlock(choices=[('left', 'Left'), ('right', 'Right')])), ('image_margin', wagtail.blocks.BooleanBlock(default=False, required=False)), ('top_padding', wagtail.blocks.BooleanBlock(default=True, required=False)), ('bottom_padding', wagtail.blocks.BooleanBlock(default=True, required=False))]))], blank=True, null=True, use_json_field=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('pages.basepage',),
        ),
    ]
