# Generated by Django 4.2.7 on 2023-11-20 11:24

from django.db import migrations
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks
import wagtailutils.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_homepage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basicpage',
            name='body',
            field=wagtail.fields.StreamField([('only_text', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(required=False)), ('text', wagtailutils.blocks.RichTextBlock(required=True))])), ('image_and_text', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(required=False)), ('text', wagtailutils.blocks.RichTextBlock(required=False)), ('image', wagtail.images.blocks.ImageChooserBlock(help_text='Optimal Dimension : 441x400', rendition_rules={'original': 'fill-441x400-c0|format-webp', 'original_fallback': 'fill-441x400-c0'}, required=False)), ('image_alignment', wagtail.blocks.ChoiceBlock(choices=[('left', 'Left'), ('right', 'Right')])), ('image_margin', wagtail.blocks.BooleanBlock(default=False, required=False)), ('top_padding', wagtail.blocks.BooleanBlock(default=True, required=False)), ('bottom_padding', wagtail.blocks.BooleanBlock(default=True, required=False))])), ('focus_Banner', wagtail.blocks.StructBlock([('mega_image', wagtailutils.blocks.ImageChooserBlock(help_text='Optimal Dimension : 986x493', rendition_rules={'original': 'fill-986x493-c0|format-webp', 'original_fallback': 'fill-986x493-c0'}, required=True)), ('baby_image', wagtailutils.blocks.ImageChooserBlock(help_text='Optimal Dimension : max width 250px', rendition_rules={'original': 'width-250|scale-100|format-webp', 'original_fallback': 'width-250|scale-100'}, required=False))]))], blank=True, null=True, use_json_field=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='body',
            field=wagtail.fields.StreamField([('only_text', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(required=False)), ('text', wagtailutils.blocks.RichTextBlock(required=True))])), ('image_and_text', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(required=False)), ('text', wagtailutils.blocks.RichTextBlock(required=False)), ('image', wagtail.images.blocks.ImageChooserBlock(help_text='Optimal Dimension : 441x400', rendition_rules={'original': 'fill-441x400-c0|format-webp', 'original_fallback': 'fill-441x400-c0'}, required=False)), ('image_alignment', wagtail.blocks.ChoiceBlock(choices=[('left', 'Left'), ('right', 'Right')])), ('image_margin', wagtail.blocks.BooleanBlock(default=False, required=False)), ('top_padding', wagtail.blocks.BooleanBlock(default=True, required=False)), ('bottom_padding', wagtail.blocks.BooleanBlock(default=True, required=False))]))], blank=True, null=True, use_json_field=True),
        ),
    ]
